[tool.poetry]
name = "quicklck"
version = "0.1.0"
description = "Quick luck S2Q"
authors = ["JogfeeingVI <lifelse@outlook.com>"]
license = "GLP3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
